# Generated by Django 5.2.3 on 2025-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quilometragem', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
